"""Add column to store prices of menu items

Revision ID: a08cd805e41a
Revises: e980524c081a
Create Date: 2016-12-23 01:29:48.802710

"""

# revision identifiers, used by Alembic.
revision = 'a08cd805e41a'
down_revision = 'e980524c081a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_entries', sa.Column('price', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_entries', 'price')
    ### end Alembic commands ###
