"""Add a column to store the allergens of each menu entry.

Revision ID: e980524c081a
Revises: db2754bfb7bc
Create Date: 2016-12-22 17:21:57.476284

"""

# revision identifiers, used by Alembic.
revision = 'e980524c081a'
down_revision = 'db2754bfb7bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_entries', sa.Column('allergens', sa.String(length=64), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_entries', 'allergens')
    ### end Alembic commands ###
